name: Android CI Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Flutter 环境（你的项目是 Flutter）
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      # 上传 APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: WatchMsg
          path: build/app/outputs/flutter-apk/WatchMsg.apk